version: '3'
services:
    blockscout:
      container_name: "blockscout"
      image: "docker.pkg.github.com/stavdev/blockscout-docker-compose/blockscout-docker-compose:main"
      networks:
        - database
      ports:
        - "4000:4000"
      depends_on:
        - postgres
    postgres:
      container_name: "postgres_blockscout"
      image: "postgres"
      networks:
        - database
      environment:
        POSTGRES_USER: blockscout
        POSTGRES_PASSWORD: blockscout
        POSTGRES_DB: blockscout
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
networks:
  database:
    driver: "bridge"