version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    networks:
      - database
    env_file:
      - database.env
    ports:
      - "5433:5433"

  blockscout:
    image: "docker.pkg.github.com/stavdev/blockscout-docker/blockscout-docker:main"
    networks:
      - database
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    tty: true
    environment:
      - MIX_ENV: "prod"
      - SECRET_KEY_BASE: "VTIB3uHDNbvrY0+60ZWgUoUBKDn9ppLR8MI4CpRz4/qLyEFs54ktJfaNT6Z221No"
      - DATABASE_URL: postgresql://postgres:12345@postgres:5433/blockscout?ssl=false
    expose:
      - "4000"
networks:
  database:
    driver: "bridge"