version: '3'
services:
  db:
    image: "postgres:latest"
    networks:
      - blockscout
    environment:
      POSTGRES_USER: blockscout
      POSTGRES_PASSWORD: blockscout
      POSTGRES_DB: default_database
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    expose:
      - "5433"

  blockscout:
    image: "docker.pkg.github.com/stavdev/blockscout-docker/blockscout-docker:main"
    networks:
      - blockscout
    ports:
      - "4000:4000"
    depends_on:
      - db
    tty: true
    environment:
      # COIN: "TMY"
      MIX_ENV: "prod"
      SECRET_KEY_BASE: "VTIB3uHDNbvrY0+60ZWgUoUBKDn9ppLR8MI4CpRz4/qLyEFs54ktJfaNT6Z221No"
      # ETHEREUM_JSONRPC_VARIANT: "geth"
      DATABASE_URL: postgresql://blockscout:blockscout@db:5433/blockscout?ssl=false
      # ETHEREUM_JSONRPC_HTTP_URL: http://database:8545
      # ETHEREUM_JSONRPC_WS_URL: http://database:8546
    expose:
      - "4000"
networks:
  blockscout:
    driver: "bridge"