version: '3'
services:
  postgres:
    container_name: "postgres_blockscout"
    image: postgres:latest
    restart: always
    networks:
      - database
    restart: always
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5433"
    expose:
      - "5433"

  blockscout:
    container_name: "blockscout"
    image: "docker.pkg.github.com/stavdev/blockscout-docker/blockscout-docker:main"
    restart: always
    networks:
      - database
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    tty: true
    environment:
      MIX_ENV: "prod"
      SECRET_KEY_BASE: "VTIB3uHDNbvrY0+60ZWgUoUBKDn9ppLR8MI4CpRz4/qLyEFs54ktJfaNT6Z221No"
      DATABASE_URL: postgresql://postgres:postgres@postgres:5433/postgres?ssl=false
networks:
  database:
    driver: "bridge"